# Generated by Django 5.0.7 on 2024-10-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_user_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Default users avatar')),
                ('project_name', models.CharField(default='', max_length=100, verbose_name='Project name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Dark Logo')),
                ('level_payments', models.JSONField(blank=True, default=list, null=True)),
                ('currency_coin_payments', models.CharField(default='USDT.TRC20', max_length=20, verbose_name='Currency abbreviation')),
                ('minimum_investment_amount', models.PositiveIntegerField(default=500, verbose_name='Minimun investment amount')),
                ('min_withdrawal_amount', models.IntegerField(default=20, verbose_name='Minimum withdrawal amount')),
                ('root_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General settings',
                'verbose_name_plural': 'General settings',
            },
        ),
    ]
