# Generated by Django 5.0.7 on 2025-07-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='network_payments',
            field=models.CharField(default='BEP20', max_length=10, verbose_name='Network payments'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='receiver_wallet',
            field=models.CharField(default='', max_length=200, verbose_name='Receiver wallet'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='currency_coin_payments',
            field=models.CharField(default='USDT.BEP20', max_length=20, verbose_name='Currency abbreviation'),
        ),
    ]
