# Generated by Django 5.0.7 on 2025-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generalsettings_network_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='withdrawal_week_days',
            field=models.JSONField(default=[5, 6], verbose_name='Withdrawal days'),
        ),
    ]
