# Generated by Django 5.0.7 on 2025-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generalsettings_withdrawal_week_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='daily_payment',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Daily payment'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='withdrawal_week_days',
            field=models.JSONField(default=list, verbose_name='Withdrawal days'),
        ),
    ]
