# Generated by Django 5.0.7 on 2025-07-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generalsettings_daily_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='investment_blocked_days',
            field=models.SmallIntegerField(default=30, verbose_name='Blocked days for investment'),
        ),
    ]
