# Generated by Django 5.0.7 on 2025-08-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generalsettings_investment_blocked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='offset_amount_payments',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Diferencia maxima aceptada entre pagos'),
        ),
    ]
