# Generated by Django 5.0.7 on 2025-10-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_generalsettings_offset_amount_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='min_fiat_withdrawable',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
