# Generated by Django 5.0.7 on 2025-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_generalsettings_min_fiat_withdrawable'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='disable_deposits',
            field=models.BooleanField(default=False, verbose_name='Deshabilitar depositos de la plataforma'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='disable_deposits_message',
            field=models.TextField(default='', verbose_name='Mensaje que se muestra al deshabilitar los despositos'),
        ),
    ]
