# Generated by Django 5.0.7 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_generalsettings_disable_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='reinvestment_week_days',
            field=models.JSONField(default=list, verbose_name='Reinvestment days'),
        ),
    ]
