# Generated by Django 5.0.7 on 2025-12-03 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_generalsettings_reinvestment_week_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPercentageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this percentage group', max_length=100, verbose_name='Group name')),
                ('percentage', models.DecimalField(decimal_places=4, help_text='Custom daily payment percentage for users in this group', max_digits=12, verbose_name='Daily payment percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Only active groups will be applied', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who will receive this custom percentage', related_name='percentage_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Custom percentage group',
                'verbose_name_plural': 'Custom percentage groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
