# Generated by Django 5.0.7 on 2024-10-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('min_time_to_withdraw', models.DateTimeField(blank=True, null=True, verbose_name='Date to withdraw')),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Earnings')),
                ('status', models.BooleanField(default=True, verbose_name='Investment status')),
                ('withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withdrawn amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount invest')),
                ('coinpayments_response', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Refused'), ('4', 'Expired')], default='1', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('txn_id', models.CharField(blank=True, max_length=100)),
                ('pay_with_balance', models.BooleanField(default=False, verbose_name='Pay with balance')),
                ('before_investment_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Before investment value')),
                ('levels_paid', models.BooleanField(default=False)),
                ('current_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment_plans.userinvestment', verbose_name='User invest')),
            ],
            options={
                'verbose_name': 'Investment plan transaction',
                'verbose_name_plural': 'Investment plan transactions',
            },
        ),
    ]
