# Generated by Django 5.0.7 on 2025-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplantransaction',
            name='available_for_withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available for withdrawal date'),
        ),
        migrations.AddField(
            model_name='investmentplantransaction',
            name='withdrawn_from_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withdrawn from this deposit'),
        ),
    ]
