# Generated by Django 5.0.7 on 2025-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_plans', '0002_investmentplantransaction_available_for_withdrawal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplantransaction',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Es gratuito?'),
        ),
    ]
