# Generated by Django 5.0.7 on 2025-08-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_plans', '0003_investmentplantransaction_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplantransaction',
            name='is_reinvestment',
            field=models.BooleanField(default=False, verbose_name='Es reinversión?'),
        ),
        migrations.AlterField(
            model_name='investmentplantransaction',
            name='pay_with_balance',
            field=models.BooleanField(default=False, verbose_name='Es pagado con saldo normal?'),
        ),
    ]
