# Generated by Django 5.0.7 on 2025-12-11 00:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_plans', '0004_investmentplantransaction_is_reinvestment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvestmentPlanTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount invest')),
                ('coinpayments_response', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Refused'), ('4', 'Expired')], default='1', max_length=50)),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('txn_id', models.CharField(blank=True, max_length=100)),
                ('before_investment_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Before investment value')),
                ('levels_paid', models.BooleanField(default=False)),
                ('available_for_withdrawal_date', models.DateTimeField(blank=True, null=True, verbose_name='Available for withdrawal date')),
                ('withdrawn_from_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withdrawn from this deposit')),
                ('is_free', models.BooleanField(default=False, verbose_name='Es gratuito?')),
                ('is_reinvestment', models.BooleanField(default=False, verbose_name='Es reinversión?')),
                ('pay_with_balance', models.BooleanField(default=False, verbose_name='Es pagado con saldo normal?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('current_investment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investment_plans.userinvestment', verbose_name='User invest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Investment plan transaction',
                'verbose_name_plural': 'historical Investment plan transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserInvestment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('activation_date', models.DateTimeField(blank=True, editable=False)),
                ('min_time_to_withdraw', models.DateTimeField(blank=True, null=True, verbose_name='Date to withdraw')),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Earnings')),
                ('status', models.BooleanField(default=True, verbose_name='Investment status')),
                ('withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withdrawn amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical user investment',
                'verbose_name_plural': 'historical user investments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
