# Generated by Django 5.0.7 on 2024-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='extra_direct_payment',
            field=models.PositiveSmallIntegerField(default=0, help_text='Input extra percentage', verbose_name='Extra direct payment'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_fundator',
            field=models.BooleanField(default=False, help_text='Check if is fundator', verbose_name='Is fundator'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_direct_payment',
            field=models.PositiveSmallIntegerField(default=0, help_text='Input extra percentage', verbose_name='Extra direct payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fundator',
            field=models.BooleanField(default=False, help_text='Check if is fundator', verbose_name='Is fundator'),
        ),
    ]
