# Generated by Django 5.0.7 on 2025-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_historicaluser_extra_direct_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='investment_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Investment Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Investment Balance'),
        ),
    ]
