# Generated by Django 5.0.7 on 2025-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='bank_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Country'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Bank Swift Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Bank Swift Code'),
        ),
    ]
