# Generated by Django 5.0.7 on 2024-10-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Verification code')),
                ('status', models.CharField(choices=[('1', 'Unused'), ('2', 'Used'), ('3', 'Expired')], default='1', max_length=50, verbose_name='Code statuses')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal confirmation code',
                'verbose_name_plural': 'Withdrawal confirmation codes',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withdrawn amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Withdrawn date')),
                ('payed_date', models.DateTimeField(blank=True, null=True, verbose_name='Withdrawn payed date')),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Refused'), ('4', 'Expired')], default='1', max_length=100)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Fee')),
                ('payment_link', models.CharField(blank=True, max_length=500, verbose_name='Payment link (Tron scan)')),
                ('wallet_address', models.CharField(default='', max_length=100, verbose_name='Wallet address')),
                ('used_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='withdrawals.secretcode', verbose_name='Used code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-date'],
                'unique_together': {('user', 'used_code')},
            },
        ),
    ]
