# Generated by Django 5.0.7 on 2025-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(choices=[('1', 'Pasive withdrawal'), ('2', 'Direct withdrawal'), ('3', 'Binary withdrawal')], default='2', max_length=50),
        ),
    ]
