# Generated by Django 5.0.7 on 2025-07-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(choices=[('1', 'Utility withdrawal'), ('2', 'Balance withdrawal')], default='2', max_length=50),
        ),
    ]
