# Generated by Django 5.0.7 on 2025-08-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_alter_withdrawal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='refuse_message',
            field=models.TextField(default='', verbose_name='Mensaje de rechazo'),
        ),
    ]
