# Generated by Django 5.0.7 on 2025-08-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0004_withdrawal_refuse_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='refuse_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje de rechazo'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(choices=[('1', 'Utilidad'), ('2', 'Saldo'), ('3', 'Inversión')], default='2', max_length=50),
        ),
    ]
