# Generated by Django 5.0.7 on 2025-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0005_alter_withdrawal_refuse_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bak_bank_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Country (Bank)'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='SWIFT/BIC Code'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('fiat', 'FIAT')], default='crypto', max_length=10, verbose_name='Withdrawal Method'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Wallet address'),
        ),
    ]
