# Generated by Django 5.0.7 on 2025-10-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0006_withdrawal_bak_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='bak_bank_name',
            new_name='bank_bank_name',
        ),
    ]
