# Generated by Django 5.0.7 on 2025-10-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0007_rename_bak_bank_name_withdrawal_bank_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payment_invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
