# Generated by Django 5.0.7 on 2024-10-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Payment date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Base user payment',
                'verbose_name_plural': 'Base user payments',
            },
        ),
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('baseuserpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.baseuserpayment')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount paid')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Level payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_plans.investmentplantransaction')),
            ],
            options={
                'verbose_name': 'Direct Payment',
                'verbose_name_plural': 'Direct payments',
            },
            bases=('payments.baseuserpayment',),
        ),
        migrations.CreateModel(
            name='PasivePayment',
            fields=[
                ('baseuserpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.baseuserpayment')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Amount paid')),
                ('current_investment_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Current investment amount')),
                ('balance_investment_pasive', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Investment progress')),
                ('active_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasive_payments', to='investment_plans.userinvestment', verbose_name='Active user investment')),
            ],
            options={
                'verbose_name': 'Pasive payment',
                'verbose_name_plural': 'Pasive payments',
            },
            bases=('payments.baseuserpayment',),
        ),
    ]
