# Generated by Django 5.0.7 on 2024-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referr',
            name='is_master_code',
            field=models.BooleanField(default=False, help_text='Check for master code', verbose_name='Is master code'),
        ),
    ]
